before_script:
  - apt update && apt install -y git zip unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --no-ansi

stages:
  - test

cache:
  paths:
    - vendor/

test-71:
  image: php:7.1
  stage: test
  script:
    - composer validate --strict
    - vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
    - vendor/bin/phpstan analyze --no-progress
    - vendor/bin/phpunit

test-72:
  image: php:7.2
  stage: test
  script:
    - composer validate --strict
    - vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
    - vendor/bin/phpstan analyze --no-progress
    - vendor/bin/phpunit

test-73:
  image: php:7.3
  stage: test
  script:
    - composer validate --strict
    - vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
    - vendor/bin/phpstan analyze --no-progress
    - vendor/bin/phpunit

test-74:
  image: php:7.4
  stage: test
  script:
    - composer validate --strict
    - vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
    - vendor/bin/phpstan analyze --no-progress
    - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-php=coverage_report.php --colors=never
    - phpdbg -qrr test_coverage.php
