before_script:
  - apk add git
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --no-ansi

stages:
  - test

cache:
  paths:
    - vendor/

test-71:
  image: mileschou/xdebug:7.1
  stage: test
  script:
    - composer validate --strict
    - vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
    - vendor/bin/phpstan analyze --no-progress
    - vendor/bin/phpunit

test-72:
  image: mileschou/xdebug:7.2
  stage: test
  script:
    - composer validate --strict
    - vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
    - vendor/bin/phpstan analyze --no-progress
    - vendor/bin/phpunit

test-73:
  image: mileschou/xdebug:7.3
  stage: test
  script:
    - composer validate --strict
    - vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
    - vendor/bin/phpstan analyze --no-progress
    - vendor/bin/phpunit

test-74:
  image: mileschou/xdebug:7.4
  stage: test
  artifacts:
    paths:
      - ./coverage_report
  script:
    - composer validate --strict
    - vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff
    - vendor/bin/phpstan analyze --no-progress
    - vendor/bin/phpunit --coverage-text --coverage-php=coverage_report.php --coverage-html=coverage_report --colors=never
#    - php test_coverage.php
